# Live production stage -- the real, currently deployed target.
[vps]
einteilung.hochamt.at

[vps:vars]
app_environment=production
backend_domain=einteilung.hochamt.at
frontend_domain=einteilung.hochamt.at
shorturl_domain=go.hochamt.at
